Allow to handle labels on the nodes #148

diff --git a/kargo b/kargo
--- a/kargo
+++ b/kargo
@@ -171,8 +171,8 @@ kargo_image_load()
   kargo_read_configuration
   # check whether an agument is provided
   if [ -z "$1" ]; then
-    echo error: the command \"kargo load\" requires one argument.
-    echo usage: kargo load \<service\>
+    echo error: the command \"kargo image load\" requires one argument.
+    kargo_usage
     exit 1
   fi
   local SERVICE_NAME=${1^^}
@@ -219,9 +219,9 @@ kargo_image_save()
 {
   kargo_read_configuration
   # check whether an agument is provided
-  if [ -z "$1" ]; then
-    echo error: the command \"kargo save\" requires one argument.
-    echo usage: kargo save \<service\>
+  if [ -z $1 ]; then
+    echo error: the command \"kargo image save\" requires one argument.
+    kargo_usage
     exit 1
   fi
   local SERVICE_NAME=${1^^}
@@ -260,20 +260,30 @@ kargo_image()
 kargo_labels()
 {
   kargo_read_configuration
-  if [ -z $1 || $1 != "add" || $1 != "remove" ]; then
-    echo error: the command \"kargo labels\" requires one argument.
-    echo usage: kargo labels \<add|remove\>
+  if [ -z $1 ]; then
+    echo "error: the command \"kargo labels\" requires one argument."
+    echo "usage: kargo labels <add|remove>"
+    exit 1
+  fi
+  if [ "$1" != "add" ] && [ "$1" != "remove" ]; then
+    echo "error: the argument of the command \"kargo labels\" should be either \"add\" or \"remove\"."
+    echo "usage: kargo labels <add|remove>"
     exit 1
   fi
   for NODE in $NODES; do
-    local NODE_ID=`docker node ls | grep $NODE | awk '{print $1}'
-    local NODE_LABELS_VAR=${STACK^^}_LABELS
+    local NODE_ID=`docker node ls | grep $NODE | awk '{print $1}'`
+    local NODE_NAME=${NODE//-/_}
+    local NODE_LABELS_VAR=${NODE_NAME^^}_LABELS
     local NODE_LABELS=${!NODE_LABELS_VAR}
     for LABEL in $NODE_LABELS; do
-      if [ $1 == "add" ]; then
+      if [ "$1" == "add" ]; then
+        echo -e "  adding $LABEL to $NODE"
         docker node update --label-add $LABEL $NODE_ID > /dev/null
       else
-        docker node update --label-rm $LABEL $NODE_ID > /dev/null
+        local LABEL_KEY=`echo $LABEL | cut -d'=' -f1`
+        echo -e "  removing $LABEL_KEY from $NODE"
+        docker node update --label-rm $LABEL_KEY $NODE_ID  > /dev/null
+      fi
     done
   done
 }
